#!/bin/bash

# Unmark the 2 line below to see all commands available
#echo -e "\n$hr\nPATH COMMANDS\n$hr"
#compgen -c | xargs which -a | sort

# Adjust column numbers ('190') follow to your screen
printf -v res %190s
export hr=`printf '%s\n' "${res// /-}"`
export hrd=`printf '%s\n' "${res// /=}"`

# Run scripts
DIR=`dirname ${0}`/${1}
source /codefresh/volume/Toko-Chetabahana/branches/.google/list_files
for i in $DIR .io/$DIR; do read_files $i; done
