version: "2"

services:
  redis:
    image: redis
    restart: unless-stopped
    user: redis:redis
    volumes:
      - redis_data:/data
    networks:
      - network_tier
    deploy:
      placement:
        constraints: [node.role == manager]

  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - psql_data:/var/lib/postgresql
    networks:
      - network_tier
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  redis_data:
    driver: local
  psql_data:
    driver: local
    
networks:
  network_tier:
    driver: bridge
