steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args: [$_INIT]
  id: gcloud
    
- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args: [$_INIT]
  id: docker

options:
  env:
  - BUILD_ID=$BUILD_ID
  - PROJECT_ID=$PROJECT_ID
  - REPO_NAME=$REPO_NAME
  - BRANCH_NAME=$BRANCH_NAME
  - TAG_NAME=$TAG_NAME
  volumes:
  - name: outputs
    path: /builder/outputs/volume
  
substitutions:
  _VERSION: v1-261650-cron
  _INIT: .google/cloud/builders/__init__

tags: [mytag1, mytag2]
timeout: 100s
