steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: /bin/bash
  args: [$_INIT]
  env:
  - TAG_NAME=gcloud
    
- name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args: [$_INIT]
  env:
  - TAG_NAME=docker

- name: python
  entrypoint: /bin/bash
  args: [$_INIT]
  env:
  - TAG_NAME=python

options:
  env:
  - BUILD_ID=$BUILD_ID
  - PROJECT_ID=$PROJECT_ID
  - TAG_NAME=$TAG_NAME
  - REPO_NAME=$REPO_NAME
  - BRANCH_NAME=$BRANCH_NAME
  - OUTPUTS_VOLUME=$_OUTPUT
  volumes:
  - name: outputs-volume
    path: /builder/outputs/volume
  
substitutions:
  _INIT: .google/cloud/builders/__init__
  _OUTPUT: /builder/outputs/volume
  _VERSION: v1-1908130526-173f1d12-6377-4db0-b9e0-4049b866eec6-gcp

tags: [mytag1, mytag2, mytag3]
timeout: 100s
