steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['$_INIT', '$BUILD_ID', '$PROJECT_ID', '$REPO_NAME', '$BRANCH_NAME', '$TAG_NAME']
  id: 'gcloud'
  entrypoint: 'bash'
    
- name: 'gcr.io/cloud-builders/docker'
  args: ['$_INIT', '$BUILD_ID', '$PROJECT_ID', '$REPO_NAME', '$BRANCH_NAME', '$TAG_NAME']
  id: 'docker'
  entrypoint: 'bash'

options:
  volumes:
  - name: 'outputs'
    path: /builder/outputs/volume
    
substitutions:
  _VERSION: 'v1-091924-cron'
  _INIT: .google/cloud/builders/__init__

tags: ['mytag1', 'mytag2']
timeout: '100s'
