steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: /bin/bash
  args: [$_INIT]
  id: gcloud
    
- name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args: [$_INIT]
  id: docker

options:
  env:
  - BUILD_ID=$BUILD_ID
  - PROJECT_ID=$PROJECT_ID
  - TAG_NAME=$TAG_NAME
  - REPO_NAME=$REPO_NAME
  - BRANCH_NAME=$BRANCH_NAME
  - OUTPUT_VOLUME=$_OUTPUT
  volumes:
  - name: outputs
    path: /builder/outputs/volume
  
substitutions:
  _INIT: .google/cloud/builders/__init__
  _OUTPUT: /builder/outputs/volume
  _VERSION: v1-101344-b47655d7-b517-4ca6-95f9-46a265f2bc94-gcp

tags: [mytag1, mytag2]
timeout: 100s
