steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        bash ${_INIT} $BUILD_ID $PROJECT_ID \
        $REPO_NAME $BRANCH_NAME $TAG_NAME \;
        
- name: 'python'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        bash ${_INIT} $BUILD_ID $PROJECT_ID \
        $REPO_NAME $BRANCH_NAME $TAG_NAME \;

substitutions:
  _VERSION: 'v1-311843-cron'
  _INIT: branches/.codefresh/pipeline/__init__
  
timeout: '1000s'
