steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: /bin/bash
  args: [$_INIT]
  id: gcloud
    
- name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args: [$_INIT]
  id: docker

options:
  env:
  - BUILD_ID=$BUILD_ID
  - PROJECT_ID=$PROJECT_ID
  - TAG_NAME=$TAG_NAME
  - REPO_NAME=$REPO_NAME
  - BRANCH_NAME=$BRANCH_NAME
  - OUTPUTS_VOLUME=$_OUTPUT
  volumes:
  - name: outputs-volume
    path: /builder/outputs/volume
  
substitutions:
  _INIT: .google/cloud/builders/__init__
  _OUTPUT: /builder/outputs/volume
  _VERSION: v1-101529-0724503a-ea8d-4976-9754-c60ce8124054-gcp

tags: [mytag1, mytag2]
timeout: 100s
