steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: /bin/bash
  args: [$_INIT]
  env:
  - TAG_NAME=gcloud
  id: gcloud
    
- name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args: [$_INIT]
  env:
  - TAG_NAME=docker
  id: docker

- name: python
  entrypoint: /bin/bash
  args: [$_INIT]
  env:
  - TAG_NAME=python
  id: python

options:
  env:
  - BUILD_ID=$BUILD_ID
  - PROJECT_ID=$PROJECT_ID
  - TAG_NAME=$TAG_NAME
  - REPO_NAME=$REPO_NAME
  - BRANCH_NAME=$BRANCH_NAME
  - OUTPUTS_VOLUME=$_OUTPUT
  volumes:
  - name: outputs-volume
    path: /builder/outputs/volume
  
substitutions:
  _INIT: .google/cloud/builders/__init__
  _OUTPUT: /builder/outputs/volume
  _VERSION: v1-1908131137-1906eb24-17f4-4bae-8b34-a35a6f07e11d-gcp

tags: [mytag1, mytag2, mytag3]
timeout: 100s
