version: '1.0'
stages:
  - stage1
steps:
  read_cf:
    title: 'cf info build'
    image: codefresh/cli
    commands:
      - printenv | sort
      - codefresh get build $CF_BUILD_ID
      - rm -rf ${CF_VOLUME_PATH}/${CF_REPO_NAME} ${CF_VOLUME_PATH}/$WORKSPACE
      - printf -v res %190s && cf_export hr=$(printf '%s\n' "${res// /-}") && cf_export hrd=$(printf '%s\n' "${res// /=}")

  read_gcloud:
    title: 'gcloud build'
    image: chetabahana/gcloud-kms
    commands:
      - printenv | sort
      - ls -al

  main_clone:
    title: 'Python test'
    stage: stage1
    image: python:latest
    commands:
      - LOWER="`echo ${CF_REPO_OWNER} | tr '[:upper:]' '[:lower:]'`"
