version: '1.0'
stages:
  - stage1
steps:
  cli:
    title: 'cf info build'
    image: codefresh/cli
    commands:
      - REPO_FLOW=Toko-Chetabahana && rm -rf .io .root $REPO_FLOW $CF_REPO_NAME
      - mkdir .root && cf_export ROOT=$(realpath .root) OUTPUTS_VOLUME=$CF_VOLUME_PATH
      - cf_export BUILD_ID=$CF_BUILD_ID PROJECT_ID=$CF_ACCOUNT BRANCH_NAME=$CF_BRANCH REPO_NAME$=CF_REPO_NAME
      - git clone https://github.com/MarketLeader/$REPO_FLOW.git && cf_export INIT=$REPO_FLOW/.google/cloud/builders/__init__

  gcloud:
    title: 'gcloud build'
    image: gcr.io/cloud-builders/gcloud
    commands:
      - printenv | sort
      - bash $INIT 
      #- cp -frpT $HOME $ROOT

  python:
    title: 'python test'
    stage: stage1
    image: python:latest
    commands:
      #- cp -frpT $ROOT $HOME
      #- bash $INIT $CF_BUILD_ID $CF_ACCOUNT $CF_REPO_NAME $CF_BRANCH $CF_STEP_NAME
      - printenv | sort
