version: '1.0'
stages:
  - stage1
steps:
  read_cf:
    title: 'cf info build'
    image: codefresh/cli
    commands:
      - printenv | sort
      - codefresh get build $CF_BUILD_ID
      - rm -rf ${CF_VOLUME_PATH}/${CF_REPO_NAME}

  read_gcloud:
    title: 'gcloud build'
    image: google/cloud-sdk:alpine
    commands:
      - git clone https://github.com/MarketLeader/Toko-Chetabahana.git    
      - bash Toko-Chetabahana/scripts/cloud_builder.sh gcloud

  main_clone:
    title: 'Python test'
    stage: stage1
    image: python:latest
    commands:
      - git clone https://github.com/$CF_REPO_OWNER/$CF_REPO_NAME.git    
      - cf_export WORKSPACE=$(realpath $CF_REPO_NAME) && cd $WORKSPACE
      - bash $WORKSPACE/scripts/cloud_builder.sh python
