version: '1.0'
stages:
  - stage1
steps:
  cli:
    title: 'cf info build'
    image: codefresh/cli
    commands:
      - cf_export PROJECT_ID=$(echo "$CF_REPO_OWNER" | tr '[:upper:]' '[:lower:]')
      - rm -rf .io .root $CF_REPO_NAME && mkdir .root && cf_export ROOT=$(realpath .root)
      - git clone https://github.com/CF_REPO_OWNER/$CF_REPO_NAME.git && cf_export REPO_PATH=$(realpath $CF_REPO_NAME)
      - cf_export BUILD_ID=$CF_BUILD_ID BRANCH_NAME=$CF_BRANCH REPO_NAME=$CF_REPO_NAME OUTPUTS_VOLUME=$CF_VOLUME_PATH

  gcloud:
    title: 'gcloud build'
    image: gcr.io/cloud-builders/gcloud
    commands:
      - export TAG_NAME=gcloud && cd $REPO_PATH && bash .google/cloud/builders/__init__
      - cp -frpT $HOME $ROOT

  docker:
    title: 'docker test'
    stage: stage1
    image: gcr.io/cloud-builders/docker
    commands:
      - cp -frpT $ROOT $HOME
      - export TAG_NAME=docker && cd $REPO_PATH && bash .google/cloud/builders/__init__

  python:
    title: 'python test'
    stage: stage1
    image: python:latest
    commands:
      - cp -frpT $ROOT $HOME
      - export TAG_NAME=python && cd $REPO_PATH && bash .google/cloud/builders/__init__
