version: '1.0'
stages:
  - stage1
steps:
  cli:
    title: 'cf info build'
    image: codefresh/cli
    commands:
      - PROJECT_ID=$(echo "$a" | tr '[:upper:]' '[:lower:]')
      - cf_export PROJECT_ID=$PROJECT_ID BUILD_ID=$CF_BUILD_ID BRANCH_NAME=$CF_BRANCH REPO_NAME=$CF_REPO_NAME
      - git clone https://github.com/MarketLeader/$CF_REPO_NAME.git && cf_export REPO_PATH=$(realpath $CF_REPO_NAME)
      - rm -rf .io .root $CF_REPO_NAME && mkdir .root && cf_export ROOT=$(realpath .root) OUTPUTS_VOLUME=$CF_VOLUME_PATH

  gcloud:
    title: 'gcloud build'
    image: gcr.io/cloud-builders/gcloud
    commands:
      - export TAG_NAME=gcloud && cd $REPO_PATH && bash .google/cloud/builders/__init__
      #- cp -frpT $HOME $ROOT

  python:
    title: 'python test'
    stage: stage1
    image: python:latest
    commands:
      #- cp -frpT $ROOT $HOME
      - export TAG_NAME=python && cd $REPO_PATH && bash .google/cloud/builders/__init__
