#!/bin/bash

# Unmark the 2 line below to see all commands available
#echo -e "\n$hr\nPATH COMMANDS\n$hr"
#compgen -c | xargs which -a | sort && dpkg -l

# Adjust column numbers ('180') follow to your screen
printf -v res %180s
export hr=`printf '%s\n' "${res// /_}"`
export hrd=`printf '%s\n' "${res// /=}"`

# Environtment
export PATH=$HOME/.local/bin:$PATH

# Check active gcloud
if [[ "${TAG_NAME}" == "gcloud" ]]
then
	# Set Google App Credentials
	gcloud config get-value account
    if [[ -z $(gcloud config get-value account) ]]
    then
    echo gcloud account none
        # Dependencies: GCP_ACCOUNT & GCP_SA_KEY
        if [ -z $GOOGLE_APPLICATION_CREDENTIALS ]
        then
            echo GCP_SA_KEY
            echo $GCP_SA_KEY > google-app-creds.json
            export KEY_FILE=$(realpath google-app-creds.json)
    	    gcloud auth activate-service-account $GCP_ACCOUNT --key-file=$KEY_FILE --project=$PROJECT_ID
    	fi
    fi
fi

# Run the current step
source .google/list_files
read_files ${0%/*}/$TAG_NAME
