#!/bin/bash

# Unmark the 2 line below to see all commands available
#echo -e "\n$hr\nPATH COMMANDS\n$hr"
#compgen -c | xargs which -a | sort && dpkg -l

# Adjust column numbers ('180') follow to your screen
printf -v res %180s
export hr=`printf '%s\n' "${res// /_}"`
export hrd=`printf '%s\n' "${res// /=}"`

# Environtment
export PATH=$HOME/.local/bin:$PATH

# Run the current step
source .google/list_files
read_files ${0%/*}/$TAG_NAME
