#!/bin/bash

# Read environtment 
read_lines() {
    # Reading..
    if [ -f $1 ]
    then
        while read -r line; do
            line=$(sed -e 's/[[:space:]]*$//' <<<${line})
            var=`echo $line | cut -d '=' -f1`; test=$(echo $var)
            if [ -z "$(test)" ];then eval export "$line";fi
        done <$1
    fi
}

# Running each scripts
run_script() {
    # Looping..
    read_lines $HOME/.ssh/env_keys
    # Calling..
    echo -e "$hrd\nRUN SCRIPT:\n$1\n$hr"
    sh $1; rm -f .io/$1;
}

# Listing script files to run
read_files() {
    [[ $1 == *"io/"* ]] && TYPE=CUSTOM || TYPE=COMMON
    echo -e "\n$hrd\n$TYPE SCRIPTS\n$hrd"
    if ([ -d $1 ] && [ "$(ls -A $1)" ])
    then
        # Listing..
        chmod -R +x $1/*
        ls -l $1 | grep ".sh" && echo -e "\n$hr\n"
        # Running..
        find $1 -type f -name '*.sh' | sort | \
        while read file; do run_script "$file"; done
    else
        echo -e "No '$TYPE' scripts to run\n$hr"	
    fi
}
