steps:
- name: '${_SOURCE}/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        bash ${_SCRIPT}/gcloud.bash $PROJECT_ID \
        $REPO_NAME $BRANCH_NAME $BUILD_ID $COMMIT_SHA \
        ${_BUILD_DIR} ${_USER_NAME} ${_USER_EMAIL} ${_USER_REPO}

- name: '${_SOURCE}/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        bash ${_SCRIPT}/git.bash ${PROJECT_ID} \
        $REPO_NAME $BRANCH_NAME $BUILD_ID $COMMIT_SHA \
        ${_BUILD_DIR} ${_USER_NAME} ${_USER_EMAIL} ${_USER_REPO}

substitutions:
  _VERSION: 'v1-290549-cron'
  _BUILD_DIR: /workspace/home
  _SOURCE: gcr.io/cloud-builders
  _SCRIPT: /workspace/scripts/gcb

timeout: "1800s"
