steps:
- name: '${_SOURCE}/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        find . -type f -name gcloud.env -exec bash {} $BUILD_ID \
        $PROJECT_ID $REPO_NAME $BRANCH_NAME $TAG_NAME \;
        
- name: '${_SOURCE}/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        find . -type f -name docker.env -exec bash {} $BUILD_ID \
        $PROJECT_ID $REPO_NAME $BRANCH_NAME $TAG_NAME \;

substitutions:
  _VERSION: 'v1-170051-cron'
  _SOURCE: gcr.io/cloud-builders

timeout: '60s'
