version: '1.0'
stages:
  - stage1
steps:
  read_cf:
    title: 'cf info build'
    image: codefresh/cli
    commands:
      - printenv | sort
      - rm -rf Toko-Chetabahana $CF_REPO_NAME
      - cf_export INIT=branches/.codefresh/pipeline/builders/__init__ 

  read_gcloud:
    title: 'gcloud build'
    image: google/cloud-sdk:alpine
    commands:
      - git clone https://github.com/MarketLeader/Toko-Chetabahana.git    
      - cf_export WORKFLOW=$(realpath Toko-Chetabahana) 
      - bash Toko-Chetabahana/$INIT gcloud

  main_clone:
    title: 'python test'
    stage: stage1
    image: python:latest
    commands:
      - bash $WORKFLOW/$INIT python
