steps:
- name: 'google/cloud-sdk:alpine'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        bash scripts/io.bash $BUILD_ID $PROJECT_ID \
        $REPO_NAME $BRANCH_NAME $TAG_NAME ${_SOURCE} \;
        
- name: 'python'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        bash scripts/io.bash $BUILD_ID $PROJECT_ID \
        $REPO_NAME $BRANCH_NAME $TAG_NAME ${_SOURCE} \;
        
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        bash scripts/io.bash $BUILD_ID $PROJECT_ID \
        $REPO_NAME $BRANCH_NAME $TAG_NAME ${_SOURCE} \;

substitutions:
  _VERSION: 'v1-170923-cron'
  _SOURCE: cfcr.io/pipeline

timeout: '1000s'
