version: '1.0'
stages:
  - stage1
steps:
  read_cf:
    title: 'cf info build'
    image: codefresh/cli
    commands:
      - REPO_TASK=Cloud-Tasks-API
      - rm -rf .io .root $REPO_TASK $CF_REPO_NAME
      - mkdir .root && cf_export ROOT=$(realpath .root)
      - cf_export INIT=$REPO_TASK/.google/cloud/builders/__init__
      - git clone https://github.com/MarketLeader/$REPO_TASK.git

  read_gcloud:
    title: 'gcloud build'
    image: gcr.io/cloud-builders/gcloud
    commands:
      - bash $INIT gcloud && cp -frpT $HOME $ROOT

  main_clone:
    title: 'python test'
    stage: stage1
    image: python:latest
    commands:
      - cp -frpT $ROOT $HOME && bash $INIT python
