steps:
- name: '${_SOURCE}/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        echo -e '\nPROFILE\n' && git --version
        bash ${_SCRIPT}/git.bash ${PROJECT_ID} ${BRANCH_NAME}

- name: '${_SOURCE}/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        echo -e "\nGCLOUD\n" && gcloud version
        bash ${_SCRIPT}/gcloud.bash ${PROJECT_ID} ${_BUILD_DIR} ${_BUILD_HOME} ${_INSTANCE_ZONE} ${BRANCH_NAME}

- name: '${_SOURCE}/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        echo -e "\nDOCKER\n" && docker version
        bash ${_SCRIPT}/docker.bash ${PROJECT_ID} ${_INSTANCE_ZONE} ${BRANCH_NAME}

substitutions:
  _VERSION: 'v1-231508-cron'
  _BUILD_HOME: /builder/home
  _BUILD_DIR: /workspace/home
  _SCRIPT: /workspace/scripts
  _INSTANCE_ZONE: us-central1-c
  _SOURCE: gcr.io/cloud-builders

timeout: '1800s'
