steps:
- name: 'python'
  args: ['bash', './scripts/ssh.bash']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', '--zone', '${_ZONE}', '${_INSTANCE_NAME}', 
         '--command', 'sh ${_INSTANCE_PATH}/.docker/init.sh']

substitutions:
  _ZONE: us-central1-c
  _LOCAL_PATH: /workspace/.docker
  _INSTANCE_PATH: /home/chetabahana
  _INSTANCE_NAME: chetabahana@backend
  _REPOSITORY: https://github.com/mirumee/saleor.git
  _BUILD_ID: 'v1-111520-cron'

timeout: "1800s"
