steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        git clone https://source.developers.google.com/p/chetabahana/r/github_chetabahana_branches
        mv -f github_chetabahana_branches/home /workspace
        rm -rf github_chetabahana_branches

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        gcloud kms decrypt --location global --keyring my-keyring --key github-key \
        --plaintext-file ${_LOCAL_PATH}/.ssh/id_rsa --ciphertext-file ${_LOCAL_PATH}/.ssh/id_rsa.enc
        gcloud kms decrypt --location global --keyring my-keyring --key google-compute-engine-key \
        --plaintext-file ${_LOCAL_PATH}/.ssh/google_compute_engine \
        --ciphertext-file ${_LOCAL_PATH}/.ssh/google_compute_engine.enc 

- name: 'python'
  args: ['bash', '/workspace/scripts/main.bash']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', '--zone', '${_ZONE}', '${_INSTANCE_NAME}',
         '--command', 'sh ${_INSTANCE_PATH}/.docker/init.sh']

substitutions:
  _ZONE: us-central1-c
  _BUILD_ID: 'v1-251452-cron'
  _INSTANCE_PATH: /home/chetabahana
  _INSTANCE_NAME: chetabahana@backend
  _LOCAL_PATH: /workspace/home/chetabahana

timeout: "1800s"
