steps:
- name: '${_SOURCE}/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        bash ${_SCRIPT}/gcloud.bash $PROJECT_ID \
        $REPO_NAME $BRANCH_NAME $BUILD_ID ${_BUILD_DIR}

- name: '${_SOURCE}/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        bash ${_SCRIPT}/docker.bash ${PROJECT_ID} \
        $REPO_NAME $BRANCH_NAME $BUILD_ID ${_BUILD_DIR}

substitutions:
  _VERSION: 'v1-062105-cron'
  _BUILD_HOME: /builder/home
  _BUILD_DIR: /workspace/home
  _SOURCE: gcr.io/cloud-builders
  _SCRIPT: /workspace/scripts/gcb

timeout: '600s'
